{
 "title": "Desktop Transformation - Persona Mapping",
 "tags": [
  "uberAgent",
  "Azure Data Explorer"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "grafana-azure-data-explorer-datasource"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "database",
    "label": "Database",
    "query": {}
   },
   { "name": "User" },
   { "name": "Computer", "label": "Machine" },
   { "name": "App" },
   { "name": "browser_usage_threshold", "label": "Browser usage threshold", "query": "0" },
   { "name": "time_agg", "label": "Time aggregation", "query": "1m,5m,,10m,15m,30m,1h,1d" }
  ]
 },
 "panels": [
  { "title": "Instructions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "## 🚀 Desktop Transformation - Persona Mapping\n\nThis dashboard provides a comprehensive overview of **application inventory, usage, and performance** — essential data for planning and executing **desktop transformation initiatives**.\n\nInstead of assigning all users full personal virtual machines, you can use this data to:\n- Identify which apps are **actually used**\n- Understand the **performance impact** of those apps\n- Group users with similar needs\n- Deliver more **cost-effective, tailored desktop experiences**\n\n---\n\n## 🔍 Dashboard Structure — Each Row Answers a Key Question\n\n1. **What apps are installed?**  \n   → View all applications detected across endpoints and virtual machines.\n\n2. **What apps are used?**  \n   → Discover which apps are in foreground, how often, and by whom.\n\n3. **How well do these apps perform?**  \n   → Examine CPU, RAM, disk, and more metrics per app to gauge ressource consumption.\n\n4. **How are browsers being used?**  \n   → Analyze browser usage patterns to find candidates that can be assigned a browser only.\n\n---\n\n> 💡 Use filters at the top to narrow down by machine, app name, user, or time range.  \n> This dashboard helps you match **application needs to user personas**, and transition from \"one size fits all\" desktops to **right-sized solutions**.\n"
   }
  },
  {
   "title": "What apps are installed?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unique machines",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Application_ApplicationInventory\r\n| where $__timeFilter(Timestamp)\r\n| summarize count_distinct(Host)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Unique publishers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Application_ApplicationInventory\r\n| where $__timeFilter(Timestamp)\r\n| summarize count_distinct(Publisher)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Unique apps",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Application_ApplicationInventory\r\n| where $__timeFilter(Timestamp)\r\n| summarize count_distinct(DisplayName)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Total app installations",
     "type": "stat",
     "description": "The total number of times any app appears across all devices",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Application_ApplicationInventory\r\n| where $__timeFilter(Timestamp)\r\n| summarize count()",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Install count per app (top 10)",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Application_ApplicationInventory\r\n| where $__timeFilter(Timestamp)\r\n| summarize install_count = count_distinct(Host) by DisplayName\r\n| top 10 by install_count desc",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Install count per publisher (top 10)",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Application_ApplicationInventory\r\n| where $__timeFilter(Timestamp)\r\n| summarize install_count = count_distinct(Host) by Publisher\r\n| top 10 by install_count desc",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Data table",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Application_ApplicationInventory\r\n| where $__timeFilter(Timestamp)\r\n| summarize \r\nby Host, App = DisplayName, Version = DisplayVersion, Publisher = Publisher, Install_date = InstallDate, Install_location = InstallLocation\r\n| sort by Host asc, App asc, Version asc\r\n",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "What apps are used?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "App foreground usage",
     "type": "timeseries",
     "description": "Foreground apps are your most important ones. They are not only installed and running in the background, they are actively used by your users.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Session_SessionDetail\r\n| where $__timeFilter(Timestamp)\r\n| where SessionFgProcessName != \"\"\r\n| summarize Count = count() by bin(Timestamp, $time_agg), SessionFgAppId\r\n| evaluate pivot(SessionFgAppId, sum(Count))\r\n| sort by Timestamp",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "App usage data table",
     "type": "table",
     "description": "Lists all versions, users and computers by app, whether in foreground or not. Columns can be filtered.\n\nClick on an app to filter the charts below.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Process_ProcessDetail\r\n| where $__timeFilter(Timestamp)\r\n| where AppId !in (\"Microsoft Windows OS\",\"MsWnOS\",\"macOS\") \r\n| where ProcUser !in (\"sys\",\"nvc\",\"lvc\")\r\n| where AppId has \"$App\"\r\n| summarize \r\nVersions = count_distinct(AppVersion),\r\nUsers = count_distinct(ProcUser),\r\nHosts = count_distinct(Host)\r\nby App = AppId\r\n| sort by App asc\r\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Usage over time",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Process_ProcessDetail\r\n| where $__timeFilter(Timestamp)\r\n| where SessionID > 0\r\n| where AppId !in~ (\"Microsoft Windows OS\",\"MsWnOS\",\"macOS\") \r\n| where ProcUser !in~ (\"sys\",\"nvc\",\"lvc\")\r\n| where AppId has \"$App\"\r\n| summarize usage = count_distinct(ProcUser) by bin(Timestamp, $time_agg), AppId\r\n| evaluate pivot(AppId, max(usage))\r\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Usage detail",
     "type": "table",
     "description": "Select an app in the data table above to filter this chart.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Process_ProcessDetail\r\n| where $__timeFilter(Timestamp)\r\n| where AppId !in (\"Microsoft Windows OS\",\"MsWnOS\",\"macOS\") \r\n| where ProcUser !in (\"sys\",\"nvc\",\"lvc\")\r\n| where AppId has \"$App\"\r\n| summarize \r\nby App = AppId, Version = AppVersion, User = ProcUser, Machine = Host\r\n| sort by App asc, Version asc, User asc \r\n",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "App performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 94 },
     "options": {
      "content": "App performance is part of the **Troubleshooting Poor User Experience** dashboard. You can access it via the link below. "
     }
    },
    { "type": "dashlist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 112 } }
   ]
  },
  {
   "title": "How are browsers being used?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Browser in foreground >= ${browser_usage_threshold}%",
     "type": "table",
     "description": "Shows all users who had a browser in foreground more than ${browser_usage_threshold}% of the time. The threshold can be set at the dashboard's top.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Session_SessionDetail\r\n| where $__timeFilter(Timestamp)\r\n| summarize \r\ncount_fg_app = count()\r\nby SessionFgProcessName, SessionUser\r\n| join kind=inner (\r\n    Session_SessionDetail\r\n    | summarize event_count = count() by SessionUser\r\n) on SessionUser\r\n| extend app_in_foreground_percent = round( todouble(count_fg_app) / todouble(event_count) * 100, 1 )\r\n| where SessionFgProcessName in~ (\"chrome.exe\",\"msedge.exe\",\"firefox.exe\",\"iexplore.exe\",\"CitrixEnterpriseBrowser.exe\")\r\n| where app_in_foreground_percent >= $browser_usage_threshold\r\n| project user = SessionUser, browser = SessionFgProcessName, foreground = app_in_foreground_percent\r\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Used web apps",
     "type": "table",
     "description": "If the foreground window is a browser: the URL of the active tab.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "clusterUri": "$cluster",
       "database": "$database",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Session_SessionDetail\r\n| where $__timeFilter(Timestamp)\r\n| where SessionFgBrowserActiveTabHost != \"\"\r\n| summarize \r\ncount = count()\r\nby web_app = SessionFgBrowserActiveTabHost\r\n| sort by count desc\r\n",
       "querySource": "raw"
      }
     ]
    }
   ]
  }
 ]
}