{
 "title": "Troubleshooting Poor User Experience",
 "tags": [
  "uberAgent",
  "Azure Monitor"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "resource_group",
    "label": "Resource group",
    "query": {}
   },
   {
    "name": "workspace",
    "label": "Workspace",
    "query": {}
   },
   { "name": "User" },
   { "name": "Computer", "label": "Machine" },
   { "name": "App" },
   { "name": "time_agg", "label": "Time aggregation", "query": "1m,5m,10m,15m,30m,1h,1d" }
  ]
 },
 "panels": [
  { "title": "Instructions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "## 🎯 Troubleshooting Poor User Experience\n\nDiagnosing poor user experience in virtual sessions is complex — it requires analyzing multiple layers such as input responsiveness, protocol performance, system load, and network conditions. This dashboard helps simplify that process.\n\nStart by identifying sessions with **high session delay** (input delay + protocol latency), then use the lower panels to investigate **root causes** like app or network performance issues.\n\n> 💡 **Tip:** Click on a username in any data table to **filter the entire dashboard** to that specific user's session.\n\n---\n\n## 🧮 Why Percentiles Matter\n\nMost metrics in this dashboard (e.g. input delay, protocol latency, CPU, RAM, Disk) are calculated using the **80th percentile**, rather than the average or maximum.\n\n- The **80th percentile** means: \"80% of the time, values were below this number.\"\n- It helps **ignore brief spikes**, while still highlighting **consistently poor performance**.\n- It's more realistic for assessing **typical user experience** than using averages.\n\n---\n\n## 🧪 What Is Session Delay?\n\n**Session Delay** = **User Input Delay** + **Protocol Latency**\n\n- **Protocol Latency**: Measures network-related delay in remoting protocols like ICA or RDP.\n- **User Input Delay**: Captures the time between user input (e.g. keypress) and the moment it is picked up by the application — a direct indicator of system/app responsiveness.\n\n---\n\n## 📊 How To Interpret Session Delay\n\nSession delay categories used in this dashboard:\n\n- 🟢 **Excellent**: consistently **below 40 ms**\n- 🔵 **Good**: mostly below 40 ms, always **below 200 ms**\n- 🟡 **Mediocre**: consistently **below 400 ms**\n- 🔴 **Poor**: frequently **above 400 ms**\n\n> ℹ️ [More info on user input delay](https://uberagent.com/blog/uberagent-7-1-preview-user-input-delay-application-responsiveness/)"
   }
  },
  {
   "title": "Session metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Session delay overview",
     "type": "timeseries",
     "description": "The 80th percentile of protocol latency + input delay for all sessions. Gauges the overall user experience.",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Session_SessionDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where SessionUser_s != \"sys\"\r\n| where SessionUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend delay = SessionInputDelaySumMs_d/SessionInputDelayCount_d\r\n| summarize \r\ndelay = percentile(delay,80),\r\nSessionRpLatencyMs_d =  percentile(column_ifexists(\"SessionRpLatencyMs_d\", 0),80)\r\nby bin(TimeGenerated, $time_agg)\r\n| extend session_delay = delay + SessionRpLatencyMs_d\r\n| project-away delay, SessionRpLatencyMs_d\r\n\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Session count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Session_SessionDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where SessionUser_s != \"sys\"\r\n| summarize \r\nsession_count = count_distinct(SessionGUID_g)\r\nby bin(TimeGenerated, $time_agg)\r\n| sort by TimeGenerated",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Session table",
     "type": "table",
     "description": "The table lists all sessions in the selected timeframe, sorted by session delay. Click on a session to filter the dashboard.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Session_SessionDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where SessionUser_s != \"sys\"\r\n| where SessionUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend delay = SessionInputDelaySumMs_d / SessionInputDelayCount_d\r\n| summarize \r\nuser = max(SessionUser_s),\r\nmachine = max(Computer),\r\nlogon = max(SessionLogonTime_s),\r\nprotocol = max(SessionProtocol_s),\r\nstate = max(SessionConnectionState_s),\r\nclient_ip = max(column_ifexists(\"SessionClientIp_s\",\"\")),\r\nclient_name = max(column_ifexists(\"SessionClientName_s\",\"\")),\r\nclient_os = max(column_ifexists(\"SessionClientPlatform_s\",\"\")),\r\nclient_version = max(column_ifexists(\"SessionClientVersion_s\",\"\")),\r\nctx_transport = max(column_ifexists(\"SessionTransportProtocols_s\",\"\")),\r\nctx_apps = max(column_ifexists(\"SessionPublishedAppsCtx_s\",\"\")),\r\nid = max(SessionID_d),\r\ndelay = percentile(delay,80),\r\nSessionRpLatencyMs_d =  percentile(column_ifexists(\"SessionRpLatencyMs_d\", 0),80)\r\nby SessionGUID_g\r\n| extend user_machine = strcat(user,\"@\",machine)\r\n| extend user_without_ad = replace(@\"^[^\\\\]+\\\\\", \"\", user)\r\n| extend session_delay = delay + SessionRpLatencyMs_d\r\n| project user_machine, session_id = id, session_delay, state, logon, protocol, client_ip, client_name, client_os, client_version, user_without_ad, machine, ctx_transport, ctx_apps\r\n| sort by session_delay desc \r\n\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Delay per session over time",
     "type": "timeseries",
     "description": "The 80th percentile of protocol latency + input delay per session",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Session_SessionDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where SessionUser_s != \"sys\"\r\n| where SessionUser_s contains '$User'\r\n| where Computer contains \"$Computer\"\r\n| extend delay = SessionInputDelaySumMs_d / SessionInputDelayCount_d\r\n| summarize \r\ndelay = percentile(delay,80),\r\nSessionRpLatencyMs_d =  percentile(column_ifexists(\"SessionRpLatencyMs_d\", 0),80),\r\nuser = max(SessionUser_s),\r\nhost = max(Computer),\r\nid = max(SessionID_d)\r\nby bin(TimeGenerated, $time_agg), SessionGUID_g\r\n| extend user_host = strcat(user, \"(\", id, \")\",\"@\",host)\r\n| extend user_without_ad = replace(@\"^[^\\\\]+\\\\\", \"\", user)\r\n| extend latency_p80 = delay + SessionRpLatencyMs_d\r\n| project-away delay, SessionRpLatencyMs_d, SessionGUID_g, id\r\n| evaluate pivot(user_host, max(latency_p80))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "options": {
      "content": "The charts below split the **session delay** in its components: **protocol latency** and **input delay**.\n\n## High protocol latency\n\nProtocol latency is the time it takes to send a request to the VDA, or the computer where uberAgent is running on, and receive a response. A high value indicates network issues or not enough bandwidth.\n\nSpecifically for ICA sessions, the **ICA RTT** chart shows the time between user action and screen response, including ICA latency, endpoint delay, and host delay.\n\n## High input delay\n\nHigh input delay indicates that the VDA, or the computer where uberAgent is installed, has not enough resources available to process the request. It is worth checking the machine and app compute charts below, to see if the machine is overloaded or if an app is consuming too much CPU or memory.\n"
     }
    },
    {
     "title": "Protocol latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Session_SessionDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where SessionUser_s != \"sys\"\r\n| where SessionUser_s contains '$User'\r\n| where Computer contains \"$Computer\"\r\n| summarize \r\nprotocol_latency =  percentile(column_ifexists(\"SessionRpLatencyMs_d\", 0),80),\r\nuser = max(SessionUser_s),\r\nhost = max(Computer),\r\nid = max(SessionID_d)\r\nby bin(TimeGenerated, $time_agg), SessionGUID_g\r\n| extend user_host = strcat(user, \"(\", id, \")\",\"@\",host)\r\n| project-away  SessionGUID_g, id\r\n| evaluate pivot(user_host, max(protocol_latency))\r\n\r\n\r\n\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "ICA RTT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Session_SessionDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where SessionUser_s != \"sys\"\r\n| where SessionUser_s contains '$User'\r\n| where Computer contains \"$Computer\"\r\n| summarize \r\nrtt = max(column_ifexists(\"SessionRoundTripTimeMs\",0)),\r\nuser = max(SessionUser_s),\r\nhost = max(Computer),\r\nid = max(SessionID_d)\r\nby bin(TimeGenerated, $time_agg), SessionGUID_g\r\n| extend user_host = strcat(user, \"(\", id, \")\",\"@\",host)\r\n| project-away  SessionGUID_g, id\r\n| evaluate pivot(user_host, max(rtt))\r\n\r\n\r\n\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Input delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Session_SessionDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where SessionUser_s != \"sys\"\r\n| where SessionUser_s contains '$User'\r\n| where Computer contains \"$Computer\"\r\n| extend delay = SessionInputDelaySumMs_d / SessionInputDelayCount_d\r\n| summarize \r\ndelay = percentile(delay,80),\r\nuser = max(SessionUser_s),\r\nhost = max(Computer),\r\nid = max(SessionID_d)\r\nby bin(TimeGenerated, $time_agg), SessionGUID_g\r\n| extend user_host = strcat(user, \"(\", id, \")\",\"@\",host)\r\n| project-away  SessionGUID_g, id\r\n| evaluate pivot(user_host, max(delay))\r\n\r\n\r\n\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Machine compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stop errors",
     "type": "table",
     "description": "Stop errors are blue screens, power losses, and kernel panics (macOS).\n\nMore about error codes (Windows): https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-code-reference2",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "let BugCheckLookup = datatable(BugcheckCode_d:double , BugName:string) [\r\n    1,  \"APC_INDEX_MISMATCH\",\r\n    2,  \"DEVICE_QUEUE_NOT_BUSY\",\r\n    3,  \"INVALID_AFFINITY_SET\",\r\n    4,  \"INVALID_DATA_ACCESS_TRAP\",\r\n    5,  \"INVALID_PROCESS_ATTACH_ATTEMPT\",\r\n    6,  \"INVALID_PROCESS_DETACH_ATTEMPT\",\r\n    7,  \"INVALID_SOFTWARE_INTERRUPT\",\r\n    8,  \"IRQL_NOT_DISPATCH_LEVEL\",\r\n    9,  \"IRQL_NOT_GREATER_OR_EQUAL\",\r\n    10, \"IRQL_NOT_LESS_OR_EQUAL\",\r\n    11, \"NO_EXCEPTION_HANDLING_SUPPORT\",\r\n    12, \"MAXIMUM_WAIT_OBJECTS_EXCEEDED\",\r\n    13, \"MUTEX_LEVEL_NUMBER_VIOLATION\",\r\n    14, \"NO_USER_MODE_CONTEXT\",\r\n    15, \"SPIN_LOCK_ALREADY_OWNED\",\r\n    16, \"SPIN_LOCK_NOT_OWNED\",\r\n    17, \"THREAD_NOT_MUTEX_OWNER\",\r\n    18, \"TRAP_CAUSE_UNKNOWN\",\r\n    19, \"EMPTY_THREAD_REAPER_LIST\",\r\n    20, \"CREATE_DELETE_LOCK_NOT_LOCKED\",\r\n    21, \"LAST_CHANCE_CALLED_FROM_KMODE\",\r\n    22, \"CID_HANDLE_CREATION\",\r\n    23, \"CID_HANDLE_DELETION\",\r\n    24, \"REFERENCE_BY_POINTER\",\r\n    25, \"BAD_POOL_HEADER\",\r\n    26, \"MEMORY_MANAGEMENT\",\r\n    27, \"PFN_SHARE_COUNT\",\r\n    28, \"PFN_REFERENCE_COUNT\",\r\n    29, \"NO_SPIN_LOCK_AVAILABLE\",\r\n    30, \"KMODE_EXCEPTION_NOT_HANDLED\",\r\n    31, \"SHARED_RESOURCE_CONV_ERROR\",\r\n    32, \"KERNEL_APC_PENDING_DURING_EXIT\",\r\n    33, \"QUOTA_UNDERFLOW\",\r\n    34, \"FILE_SYSTEM\",\r\n    35, \"FAT_FILE_SYSTEM\",\r\n    36, \"NTFS_FILE_SYSTEM\",\r\n    37, \"NPFS_FILE_SYSTEM\",\r\n    38, \"CDFS_FILE_SYSTEM\",\r\n    39, \"RDR_FILE_SYSTEM\",\r\n    40, \"CORRUPT_ACCESS_TOKEN\",\r\n    41, \"SECURITY_SYSTEM\",\r\n    42, \"INCONSISTENT_IRP\",\r\n    43, \"PANIC_STACK_SWITCH\",\r\n    44, \"PORT_DRIVER_INTERNAL\",\r\n    45, \"SCSI_DISK_DRIVER_INTERNAL\",\r\n    46, \"DATA_BUS_ERROR\",\r\n    47, \"INSTRUCTION_BUS_ERROR\",\r\n    48, \"SET_OF_INVALID_CONTEXT\",\r\n    49, \"PHASE0_INITIALIZATION_FAILED\",\r\n    50, \"PHASE1_INITIALIZATION_FAILED\",\r\n    51, \"UNEXPECTED_INITIALIZATION_CALL\",\r\n    52, \"CACHE_MANAGER\",\r\n    53, \"NO_MORE_IRP_STACK_LOCATIONS\",\r\n    54, \"DEVICE_REFERENCE_COUNT_NOT_ZERO\",\r\n    55, \"FLOPPY_INTERNAL_ERROR\",\r\n    56, \"SERIAL_DRIVER_INTERNAL\",\r\n    57, \"SYSTEM_EXIT_OWNED_MUTEX\",\r\n    58, \"SYSTEM_UNWIND_PREVIOUS_USER\",\r\n    59, \"SYSTEM_SERVICE_EXCEPTION\",\r\n    60, \"INTERRUPT_UNWIND_ATTEMPTED\",\r\n    61, \"INTERRUPT_EXCEPTION_NOT_HANDLED\",\r\n    62, \"MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED\",\r\n    63, \"NO_MORE_SYSTEM_PTES\",\r\n    64, \"TARGET_MDL_TOO_SMALL\",\r\n    65, \"MUST_SUCCEED_POOL_EMPTY\",\r\n    66, \"ATDISK_DRIVER_INTERNAL\",\r\n    67, \"NO_SUCH_PARTITION\",\r\n    68, \"MULTIPLE_IRP_COMPLETE_REQUESTS\",\r\n    69, \"INSUFFICIENT_SYSTEM_MAP_REGS\",\r\n    70, \"DEREF_UNKNOWN_LOGON_SESSION\",\r\n    71, \"REF_UNKNOWN_LOGON_SESSION\",\r\n    72, \"CANCEL_STATE_IN_COMPLETED_IRP\",\r\n    73, \"PAGE_FAULT_WITH_INTERRUPTS_OFF\",\r\n    74, \"IRQL_GT_ZERO_AT_SYSTEM_SERVICE\",\r\n    75, \"STREAMS_INTERNAL_ERROR\",\r\n    76, \"FATAL_UNHANDLED_HARD_ERROR\",\r\n    77, \"NO_PAGES_AVAILABLE\",\r\n    78, \"PFN_LIST_CORRUPT\",\r\n    79, \"NDIS_INTERNAL_ERROR\",\r\n    80, \"PAGE_FAULT_IN_NONPAGED_AREA\",\r\n    81, \"REGISTRY_ERROR\",\r\n    82, \"MAILSLOT_FILE_SYSTEM\",\r\n    83, \"NO_BOOT_DEVICE\",\r\n    84, \"LM_SERVER_INTERNAL_ERROR\",\r\n    85, \"DATA_COHERENCY_EXCEPTION\",\r\n    86, \"INSTRUCTION_COHERENCY_EXCEPTION\",\r\n    87, \"XNS_INTERNAL_ERROR\",\r\n    88, \"FTDISK_INTERNAL_ERROR\",\r\n    89, \"PINBALL_FILE_SYSTEM\",\r\n    90, \"CRITICAL_SERVICE_FAILED\",\r\n    91, \"SET_ENV_VAR_FAILED\",\r\n    92, \"HAL_INITIALIZATION_FAILED\",\r\n    93, \"UNSUPPORTED_PROCESSOR\",\r\n    94, \"OBJECT_INITIALIZATION_FAILED\",\r\n    95, \"SECURITY_INITIALIZATION_FAILED\",\r\n    96, \"PROCESS_INITIALIZATION_FAILED\",\r\n    97, \"HAL1_INITIALIZATION_FAILED\",\r\n    98, \"OBJECT1_INITIALIZATION_FAILED\",\r\n    99, \"SECURITY1_INITIALIZATION_FAILED\",\r\n    100,\"SYMBOLIC_INITIALIZATION_FAILED\",\r\n    101,\"MEMORY1_INITIALIZATION_FAILED\",\r\n    102,\"CACHE_INITIALIZATION_FAILED\",\r\n    103,\"CONFIG_INITIALIZATION_FAILED\",\r\n    104,\"FILE_INITIALIZATION_FAILED\",\r\n    105,\"IO1_INITIALIZATION_FAILED\",\r\n    106,\"LPC_INITIALIZATION_FAILED\",\r\n    107,\"PROCESS1_INITIALIZATION_FAILED\",\r\n    108,\"REFMON_INITIALIZATION_FAILED\",\r\n    109,\"SESSION1_INITIALIZATION_FAILED\",\r\n    110,\"SESSION2_INITIALIZATION_FAILED\",\r\n    111,\"SESSION3_INITIALIZATION_FAILED\",\r\n    112,\"SESSION4_INITIALIZATION_FAILED\",\r\n    113,\"SESSION5_INITIALIZATION_FAILED\",\r\n    114,\"ASSIGN_DRIVE_LETTERS_FAILED\",\r\n    115,\"CONFIG_LIST_FAILED\",\r\n    116,\"BAD_SYSTEM_CONFIG_INFO\",\r\n    117,\"CANNOT_WRITE_CONFIGURATION\",\r\n    118,\"PROCESS_HAS_LOCKED_PAGES\",\r\n    119,\"KERNEL_STACK_INPAGE_ERROR\",\r\n    120,\"PHASE0_EXCEPTION\",\r\n    121,\"MISMATCHED_HAL\",\r\n    122,\"KERNEL_DATA_INPAGE_ERROR\",\r\n    123,\"INACCESSIBLE_BOOT_DEVICE\",\r\n    124,\"BUGCODE_NDIS_DRIVER\",\r\n    125,\"INSTALL_MORE_MEMORY\",\r\n    126,\"SYSTEM_THREAD_EXCEPTION_NOT_HANDLED\",\r\n    127,\"UNEXPECTED_KERNEL_MODE_TRAP\",\r\n    128,\"NMI_HARDWARE_FAILURE\",\r\n    129,\"SPIN_LOCK_INIT_FAILURE\",\r\n    130,\"DFS_FILE_SYSTEM\",\r\n    133,\"SETUP_FAILURE\",\r\n    139,\"MBR_CHECKSUM_MISMATCH\",\r\n    142,\"KERNEL_MODE_EXCEPTION_NOT_HANDLED\",\r\n    143,\"PP0_INITIALIZATION_FAILED\",\r\n    144,\"PP1_INITIALIZATION_FAILED\",\r\n    146,\"UP_DRIVER_ON_MP_SYSTEM\",\r\n    147,\"INVALID_KERNEL_HANDLE\",\r\n    148,\"KERNEL_STACK_LOCKED_AT_EXIT\",\r\n    150,\"INVALID_WORK_QUEUE_ITEM\",\r\n    151,\"BOUND_IMAGE_UNSUPPORTED\",\r\n    152,\"END_OF_NT_EVALUATION_PERIOD\",\r\n    153,\"INVALID_REGION_OR_SEGMENT\",\r\n    154,\"SYSTEM_LICENSE_VIOLATION\",\r\n    155,\"UDFS_FILE_SYSTEM\",\r\n    156,\"MACHINE_CHECK_EXCEPTION\",\r\n    158,\"USER_MODE_HEALTH_MONITOR\",\r\n    159,\"DRIVER_POWER_STATE_FAILURE\",\r\n    160,\"INTERNAL_POWER_ERROR\",\r\n    161,\"PCI_BUS_DRIVER_INTERNAL\",\r\n    162,\"MEMORY_IMAGE_CORRUPT\",\r\n    163,\"ACPI_DRIVER_INTERNAL\",\r\n    164,\"CNSS_FILE_SYSTEM_FILTER\",\r\n    165,\"ACPI_BIOS_ERROR\",\r\n    167,\"BAD_EXHANDLE\",\r\n    171,\"SESSION_HAS_VALID_POOL_ON_EXIT\",\r\n    172,\"HAL_MEMORY_ALLOCATION\",\r\n    173,\"VIDEO_DRIVER_DEBUG_REPORT_REQUEST\",\r\n    177,\"BGI_DETECTED_VIOLATION\",\r\n    180,\"VIDEO_DRIVER_INIT_FAILURE\",\r\n    184,\"ATTEMPTED_SWITCH_FROM_DPC\",\r\n    185,\"CHIPSET_DETECTED_ERROR\",\r\n    186,\"SESSION_HAS_VALID_VIEWS_ON_EXIT\",\r\n    187,\"NETWORK_BOOT_INITIALIZATION_FAILED\",\r\n    188,\"NETWORK_BOOT_DUPLICATE_ADDRESS\",\r\n    189,\"INVALID_HIBERNATED_STATE\",\r\n    190,\"ATTEMPTED_WRITE_TO_READONLY_MEMORY\",\r\n    191,\"MUTEX_ALREADY_OWNED\",\r\n    193,\"SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION\",\r\n    194,\"BAD_POOL_CALLER\",\r\n    196,\"DRIVER_VERIFIER_DETECTED_VIOLATION\",\r\n    197,\"DRIVER_CORRUPTED_EXPOOL\",\r\n    198,\"DRIVER_CAUGHT_MODIFYING_FREED_POOL\",\r\n    199,\"TIMER_OR_DPC_INVALID\",\r\n    200,\"IRQL_UNEXPECTED_VALUE\",\r\n    201,\"DRIVER_VERIFIER_IOMANAGER_VIOLATION\",\r\n    202,\"PNP_DETECTED_FATAL_ERROR\",\r\n    203,\"DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS\",\r\n    204,\"PAGE_FAULT_IN_FREED_SPECIAL_POOL\",\r\n    205,\"PAGE_FAULT_BEYOND_END_OF_ALLOCATION\",\r\n    206,\"DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS\",\r\n    207,\"TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE\",\r\n    208,\"DRIVER_CORRUPTED_MMPOOL\",\r\n    209,\"DRIVER_IRQL_NOT_LESS_OR_EQUAL\",\r\n    210,\"BUGCODE_ID_DRIVER\",\r\n    211,\"DRIVER_PORTION_MUST_BE_NONPAGED\",\r\n    212,\"SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD\",\r\n    213,\"DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL\",\r\n    214,\"DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION\",\r\n    215,\"DRIVER_UNMAPPING_INVALID_VIEW\",\r\n    216,\"DRIVER_USED_EXCESSIVE_PTES\",\r\n    217,\"LOCKED_PAGES_TRACKER_CORRUPTION\",\r\n    218,\"SYSTEM_PTE_MISUSE\",\r\n    219,\"DRIVER_CORRUPTED_SYSPTES\",\r\n    220,\"DRIVER_INVALID_STACK_ACCESS\",\r\n    222,\"POOL_CORRUPTION_IN_FILE_AREA\",\r\n    223,\"IMPERSONATING_WORKER_THREAD\",\r\n    224,\"ACPI_BIOS_FATAL_ERROR\",\r\n    225,\"WORKER_THREAD_RETURNED_AT_BAD_IRQL\",\r\n    226,\"MANUALLY_INITIATED_CRASH\",\r\n    227,\"RESOURCE_NOT_OWNED\",\r\n    228,\"WORKER_INVALID\",\r\n    230,\"DRIVER_VERIFIER_DMA_VIOLATION\",\r\n    231,\"INVALID_FLOATING_POINT_STATE\",\r\n    232,\"INVALID_CANCEL_OF_FILE_OPEN\",\r\n    233,\"ACTIVE_EX_WORKER_THREAD_TERMINATION\",\r\n    234,\"THREAD_STUCK_IN_DEVICE_DRIVER\",\r\n    235,\"DIRTY_MAPPED_PAGES_CONGESTION\",\r\n    236,\"SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT\",\r\n    237,\"UNMOUNTABLE_BOOT_VOLUME\",\r\n    239,\"CRITICAL_PROCESS_DIED\",\r\n    241,\"SCSI_VERIFIER_DETECTED_VIOLATION\",\r\n    242,\"HARDWARE_INTERRUPT_STORM\",\r\n    243,\"DISORDERLY_SHUTDOWN\",\r\n    244,\"CRITICAL_OBJECT_TERMINATION\",\r\n    245,\"FLTMGR_FILE_SYSTEM\",\r\n    246,\"PCI_VERIFIER_DETECTED_VIOLATION\",\r\n    247,\"DRIVER_OVERRAN_STACK_BUFFER\",\r\n    248,\"RAMDISK_BOOT_INITIALIZATION_FAILED\",\r\n    249,\"DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN\",\r\n    250,\"HTTP_DRIVER_CORRUPTED\",\r\n    252,\"ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY\",\r\n    253,\"DIRTY_NOWRITE_PAGES_CONGESTION\",\r\n    254,\"BUGCODE_USB_DRIVER\",\r\n    255,\"RESERVE_QUEUE_OVERFLOW\",\r\n    256,\"LOADER_BLOCK_MISMATCH\",\r\n    257,\"CLOCK_WATCHDOG_TIMEOUT\",\r\n    258,\"DPC_WATCHDOG_TIMEOUT\",\r\n    259,\"MUP_FILE_SYSTEM\",\r\n    260,\"AGP_INVALID_ACCESS\",\r\n    261,\"AGP_GART_CORRUPTION\",\r\n    262,\"AGP_ILLEGALLY_REPROGRAMMED\",\r\n    264,\"THIRD_PARTY_FILE_SYSTEM_FAILURE\",\r\n    265,\"CRITICAL_STRUCTURE_CORRUPTION\",\r\n    266,\"APP_TAGGING_INITIALIZATION_FAILED\",\r\n    268,\"FSRTL_EXTRA_CREATE_PARAMETER_VIOLATION\",\r\n    269,\"WDF_VIOLATION\",\r\n    270,\"VIDEO_MEMORY_MANAGEMENT_INTERNAL\",\r\n    271,\"RESOURCE_MANAGER_EXCEPTION_NOT_HANDLED\",\r\n    273,\"RECURSIVE_NMI\",\r\n    274,\"MSRPC_STATE_VIOLATION\",\r\n    275,\"VIDEO_DXGKRNL_FATAL_ERROR\",\r\n    276,\"VIDEO_SHADOW_DRIVER_FATAL_ERROR\",\r\n    277,\"AGP_INTERNAL\",\r\n    278,\"VIDEO_TDR_ERROR\",\r\n    279,\"VIDEO_TDR_TIMEOUT_DETECTED\",\r\n    281,\"VIDEO_SCHEDULER_INTERNAL_ERROR\",\r\n    282,\"EM_INITIALIZATION_FAILURE\",\r\n    283,\"DRIVER_RETURNED_HOLDING_CANCEL_LOCK\",\r\n    284,\"ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE\",\r\n    285,\"EVENT_TRACING_FATAL_ERROR\",\r\n    286,\"TOO_MANY_RECURSIVE_FAULTS\",\r\n    287,\"INVALID_DRIVER_HANDLE\",\r\n    288,\"BITLOCKER_FATAL_ERROR\",\r\n    289,\"DRIVER_VIOLATION\",\r\n    290,\"WHEA_INTERNAL_ERROR\",\r\n    291,\"CRYPTO_SELF_TEST_FAILURE\",\r\n    292,\"WHEA_UNCORRECTABLE_ERROR\",\r\n    293,\"NMR_INVALID_STATE\",\r\n    294,\"NETIO_INVALID_POOL_CALLER\",\r\n    295,\"PAGE_NOT_ZERO\",\r\n    296,\"WORKER_THREAD_RETURNED_WITH_BAD_IO_PRIORITY\",\r\n    297,\"WORKER_THREAD_RETURNED_WITH_BAD_PAGING_IO_PRIORITY\",\r\n    298,\"MUI_NO_VALID_SYSTEM_LANGUAGE\",\r\n    299,\"FAULTY_HARDWARE_CORRUPTED_PAGE\",\r\n    300,\"EXFAT_FILE_SYSTEM\",\r\n    301,\"VOLSNAP_OVERLAPPED_TABLE_ACCESS\",\r\n    302,\"INVALID_MDL_RANGE\",\r\n    303,\"VHD_BOOT_INITIALIZATION_FAILED\",\r\n    304,\"DYNAMIC_ADD_PROCESSOR_MISMATCH\",\r\n    305,\"INVALID_EXTENDED_PROCESSOR_STATE\",\r\n    306,\"RESOURCE_OWNER_POINTER_INVALID\",\r\n    307,\"DPC_WATCHDOG_VIOLATION\",\r\n    308,\"DRIVE_EXTENDER\",\r\n    309,\"REGISTRY_FILTER_DRIVER_EXCEPTION\",\r\n    310,\"VHD_BOOT_HOST_VOLUME_NOT_ENOUGH_SPACE\",\r\n    311,\"WIN32K_HANDLE_MANAGER\",\r\n    312,\"GPIO_CONTROLLER_DRIVER_ERROR\",\r\n    313,\"KERNEL_SECURITY_CHECK_FAILURE\",\r\n    314,\"KERNEL_MODE_HEAP_CORRUPTION\",\r\n    315,\"PASSIVE_INTERRUPT_ERROR\",\r\n    316,\"INVALID_IO_BOOST_STATE\",\r\n    317,\"CRITICAL_INITIALIZATION_FAILURE\",\r\n    320,\"STORAGE_DEVICE_ABNORMALITY_DETECTED\",\r\n    321,\"VIDEO_ENGINE_TIMEOUT_DETECTED\",\r\n    322,\"VIDEO_TDR_APPLICATION_BLOCKED\",\r\n    323,\"PROCESSOR_DRIVER_INTERNAL\",\r\n    324,\"BUGCODE_USB3_DRIVER\",\r\n    325,\"SECURE_BOOT_VIOLATION\",\r\n    327,\"ABNORMAL_RESET_DETECTED\",\r\n    329,\"REFS_FILE_SYSTEM\",\r\n    330,\"KERNEL_WMI_INTERNAL\",\r\n    331,\"SOC_SUBSYSTEM_FAILURE\",\r\n    332,\"FATAL_ABNORMAL_RESET_ERROR\",\r\n    333,\"EXCEPTION_SCOPE_INVALID\",\r\n    334,\"SOC_CRITICAL_DEVICE_REMOVED\",\r\n    335,\"PDC_WATCHDOG_TIMEOUT\",\r\n    336,\"TCPIP_AOAC_NIC_ACTIVE_REFERENCE_LEAK\",\r\n    337,\"UNSUPPORTED_INSTRUCTION_MODE\",\r\n    338,\"INVALID_PUSH_LOCK_FLAGS\",\r\n    339,\"KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION\",\r\n    340,\"UNEXPECTED_STORE_EXCEPTION\",\r\n    341,\"OS_DATA_TAMPERING\",\r\n    342,\"WINSOCK_DETECTED_HUNG_CLOSESOCKET_LIVEDUMP\",\r\n    343,\"KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION\",\r\n    344,\"ILLEGAL_IOMMU_PAGE_FAULT\",\r\n    345,\"HAL_ILLEGAL_IOMMU_PAGE_FAULT\",\r\n    346,\"SDBUS_INTERNAL_ERROR\",\r\n    347,\"WORKER_THREAD_RETURNED_WITH_SYSTEM_PAGE_PRIORITY_ACTIVE\",\r\n    348,\"PDC_WATCHDOG_TIMEOUT_LIVEDUMP\",\r\n    351,\"CONNECTED_STANDBY_WATCHDOG_TIMEOUT_LIVEDUMP\",\r\n    352,\"WIN32K_ATOMIC_CHECK_FAILURE\",\r\n    353,\"LIVE_SYSTEM_DUMP\",\r\n    354,\"KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE\",\r\n    355,\"WORKER_THREAD_TEST_CONDITION\",\r\n    356,\"WIN32K_CRITICAL_FAILURE\",\r\n    364,\"INVALID_RUNDOWN_PROTECTION_FLAGS\",\r\n    365,\"INVALID_SLOT_ALLOCATOR_FLAGS\",\r\n    366,\"ERESOURCE_INVALID_RELEASE\",\r\n    373,\"PREVIOUS_FATAL_ABNORMAL_RESET_ERROR\",\r\n    376,\"ELAM_DRIVER_DETECTED_FATAL_ERROR\",\r\n    391,\"VIDEO_DWMINIT_TIMEOUT_FALLBACK_BDD\",\r\n    392,\"CLUSTER_CSVFS_LIVEDUMP\",\r\n    393,\"BAD_OBJECT_HEADER\",\r\n    395,\"SECURE_KERNEL_ERROR\",\r\n    400,\"WIN32K_CRITICAL_FAILURE_LIVEDUMP\",\r\n    401,\"PF_DETECTED_CORRUPTION\",\r\n    402,\"KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL\",\r\n    403,\"VIDEO_DXGKRNL_LIVEDUMP\",\r\n    405,\"SMB_SERVER_LIVEDUMP\",\r\n    406,\"LOADER_ROLLBACK_DETECTED\",\r\n    407,\"WIN32K_SECURITY_FAILURE\",\r\n    408,\"UFX_LIVEDUMP\",\r\n    409,\"KERNEL_STORAGE_SLOT_IN_USE\",\r\n    410,\"WORKER_THREAD_RETURNED_WHILE_ATTACHED_TO_SILO\",\r\n    411,\"TTM_FATAL_ERROR\",\r\n    412,\"WIN32K_POWER_WATCHDOG_TIMEOUT\",\r\n    413,\"CLUSTER_SVHDX_LIVEDUMP\",\r\n    452,\"DRIVER_VERIFIER_DETECTED_VIOLATION_LIVEDUMP\",\r\n    453,\"IO_THREADPOOL_DEADLOCK_LIVEDUMP\",\r\n    3070, \"BC_BLUETOOTH_VERIFIER_FAULT\",\r\n    3071, \"BC_BTHMINI_VERIFIER_FAULT\",\r\n    131073,\"HYPERVISOR_ERROR\",\r\n    268435582,\"SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M\",\r\n    268435583,\"UNEXPECTED_KERNEL_MODE_TRAP_M\",\r\n    268435598,\"KERNEL_MODE_EXCEPTION_NOT_HANDLED_M\",\r\n    268435690,\"THREAD_STUCK_IN_DEVICE_DRIVER_M\",\r\n    1073741962,\"THREAD_TERMINATE_HELD_MUTEX\",\r\n    3221226008,\"STATUS_CANNOT_LOAD_REGISTRY_FILE\",\r\n    3221226010,\"STATUS_SYSTEM_PROCESS_TERMINATED\",\r\n    3221226017,\"STATUS_IMAGE_CHECKSUM_MISMATCH\",\r\n    3735936685,\"MANUALLY_INITIATED_CRASH1\"\r\n];\r\nuberAgent_System_Bugcheck_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where Computer has \"$Computer\"\r\n| join kind=leftouter BugCheckLookup on BugcheckCode_d\r\n| extend BugName = coalesce(BugName, tostring(tohex(toint(BugcheckCode_d), 4)))\r\n| summarize\r\nError = max(BugName)\r\nby bin(TimeGenerated, 1s), Computer\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "CPU usage (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_System_SystemPerformanceSummary2_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where Computer contains \"$Computer\"\r\n| summarize usage = percentile(CPUUsagePercent_d, 80) by bin(TimeGenerated, $time_agg), Computer\r\n| evaluate pivot(Computer, max(usage))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs"
       }
      }
     ]
    },
    {
     "title": "Memory usage (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_System_SystemPerformanceSummary2_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where Computer contains \"$Computer\"\r\n| summarize usage = percentile(RAMUsagePercent_d, 80) by bin(TimeGenerated, $time_agg), Computer\r\n| evaluate pivot(Computer, max(usage))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs"
       }
      }
     ]
    },
    {
     "title": "Disk utilization (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_System_SystemPerformanceSummary2_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where Computer contains \"$Computer\"\r\n| summarize usage = percentile(IOPercentDiskTime_d, 80) by bin(TimeGenerated, $time_agg), Computer\r\n| evaluate pivot(Computer, max(usage))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs"
       }
      }
     ]
    },
    {
     "title": "IO latency (sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_System_SystemPerformanceSummary2_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where Computer contains \"$Computer\"\r\n| extend io_latency = IOLatencyMsRead_d + IOLatencyMsWrite_d\r\n| summarize io_latency = sum(io_latency) by bin(TimeGenerated, $time_agg), Computer\r\n| evaluate pivot(Computer, max(io_latency))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs"
       }
      }
     ]
    },
    {
     "title": "Network utilization (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_System_SystemPerformanceSummary2_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where Computer contains \"$Computer\"\r\n| summarize usage = percentile(NetUtilizationPercent_d, 80) by bin(TimeGenerated, $time_agg), Computer\r\n| evaluate pivot(Computer, max(usage))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs"
       }
      }
     ]
    },
    {
     "title": "Pagefile usage (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_System_SystemPerformanceSummary2_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where Computer contains \"$Computer\"\r\n| summarize usage = percentile(PagefileUsagePercent_d, 80) by bin(TimeGenerated, $time_agg), Computer\r\n| evaluate pivot(Computer, max(usage))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "App compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input delay per app (p80)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessStatistics_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend delay = ProcInputDelaySumMs_d / ProcInputDelayCount_d\r\n| summarize delay = percentile(delay, 80) by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(delay))\r\n| sort by TimeGenerated",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "CPU usage (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize cpu_usage = percentile(ProcCPUPercent_d, 80) by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(cpu_usage))\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Memory usage (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize mem = percentile(ProcWorkingSetMB_d,80) by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(mem))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Disk IOs (sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize \r\nProcIOReadCount_d = sum(ProcIOReadCount_d),\r\nProcIOWriteCount_d = sum(ProcIOWriteCount_d)\r\nby bin(TimeGenerated, $time_agg), AppId_s\r\n| extend io_count = ProcIOWriteCount_d + ProcIOReadCount_d\r\n| project-away ProcIOReadCount_d, ProcIOWriteCount_d\r\n| evaluate pivot(AppId_s, max(io_count))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Network thruput (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize net = percentile(ProcNetKBPS_d,80)/1024 by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(net))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "GPU usage (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize \r\ngpu = percentile(ProcGpuComputePercent_d,80)\r\nby bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(gpu))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "GPU memory (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessDetail_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize mem = percentile(ProcGpuMemMB_d,80) by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(mem))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Handle count (sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessStatistics_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize count = sum(ProcHandleCount_d) by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(count))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Thread count (sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_ProcessStatistics_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize count = sum(ProcThreadCount_d) by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(count))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Errors & Hangs over time (sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Application_Errors_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize \r\nCrashes = sum(ErrorType_d)\r\nby bin(TimeGenerated, $time_agg), App\r\n| evaluate pivot(App, max(Crashes))\r\n| sort by TimeGenerated",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Errors & Hangs details",
     "type": "table",
     "description": "Lists all crashes and hangs by process. \n\nIf you need more granular time buckets, change the time aggregation dashboard variable.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Application_Errors_CL\r\n| where $__timeFilter(TimeGenerated)\r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend type = case(ErrorType_d == 1, \"crash\", ErrorType_d == 2, \"hang\", \"unknown\")\r\n| summarize \r\ncount = sum(ErrorType_d),\r\nmodules = make_set(ModuleName_s),\r\nexception_codes = make_set(ExceptionCode_s),\r\ntype = max(type)\r\nby bin(TimeGenerated, $time_agg), process = ProcName_s, process_version = ProcVersion_s, app = App, user = ProcUser_s, computer = Computer\r\n| project-rename time_bucket = TimeGenerated\r\n| project time_bucket, process, process_version, app, type, user, computer, count, modules, exception_codes\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "App networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP latency (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize net_latency = percentile(NetTargetSendLatencyMs_d,80) by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(net_latency))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Jitter (p80)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize net_jitter = percentile(NetTargetSendJitterMs_d,80) by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, max(net_jitter))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Receive data volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize\r\n  net_receive = sum(NetTargetReceiveMB_d)\r\n    by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, sum(net_receive))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Send data volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize\r\n  net_send = sum(NetTargetSendMB_d)\r\n    by bin(TimeGenerated, $time_agg), AppId_s\r\n| evaluate pivot(AppId_s, sum(net_send))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Data table",
     "type": "table",
     "description": "Click on an app to filter the dashboard.",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 184 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend target = coalesce(NetTargetRemoteName_s,NetTargetRemoteAddress_s)\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| summarize \r\n  latency_p80 = percentile(NetTargetSendLatencyMs_d,80),\r\n  receive_count = sum(NetTargetReceiveCount_d),\r\n  send_count = sum(NetTargetSendCount_d),\r\n  reconnect_count = sum(NetTargetReconnectCount_d),\r\n  retransmit_count = sum(NetTargetRetransmitCount_d),\r\n  send_vol = sum(NetTargetSendMB_d),\r\n  receive_vol = sum(NetTargetReceiveMB_d)\r\n  by App, Target = target, Port = NetTargetRemotePort_d\r\n| sort by App asc, Target asc \r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Latency p80 over time",
     "type": "timeseries",
     "description": "Select an app in the table above to filter this time chart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend target = coalesce(NetTargetRemoteName_s,NetTargetRemoteAddress_s)\r\n| summarize \r\n  latency_p80 = percentile(NetTargetSendLatencyMs_d,80)\r\n  by bin(TimeGenerated, $time_agg), App, Target = target, Port = NetTargetRemotePort_d\r\n| sort by App asc, Target asc , Port asc\r\n| extend target_full = strcat(App,\" -> \",Target,\":\",Port)\r\n| project TimeGenerated, target_full, latency_p80\r\n| evaluate pivot(target_full, max(latency_p80))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Receive count over time",
     "type": "timeseries",
     "description": "Select an app in the table above to filter this time chart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 208 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend target = coalesce(NetTargetRemoteName_s,NetTargetRemoteAddress_s)\r\n| summarize \r\n  receive_count = sum(NetTargetReceiveCount_d),\r\n  send_count = sum(NetTargetSendCount_d)\r\n  by bin(TimeGenerated, $time_agg), App, Target = target, Port = NetTargetRemotePort_d\r\n| sort by App asc, Target asc , Port asc\r\n| extend target_full = strcat(App,\" -> \",Target,\":\",Port)\r\n| project TimeGenerated, target_full, receive_count\r\n| evaluate pivot(target_full, max(receive_count))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Send count over time",
     "type": "timeseries",
     "description": "Select an app in the table above to filter this time chart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 216 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend target = coalesce(NetTargetRemoteName_s,NetTargetRemoteAddress_s)\r\n| summarize \r\n  send_count = sum(NetTargetSendCount_d)\r\n  by bin(TimeGenerated, $time_agg), App, Target = target, Port = NetTargetRemotePort_d\r\n| sort by App asc, Target asc , Port asc\r\n| extend target_full = strcat(App,\" -> \",Target,\":\",Port)\r\n| project TimeGenerated, target_full, send_count\r\n| evaluate pivot(target_full, max(send_count))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Reconnect count over time",
     "type": "timeseries",
     "description": "Select an app in the table above to filter this time chart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 224 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend target = coalesce(NetTargetRemoteName_s,NetTargetRemoteAddress_s)\r\n| summarize \r\n  reconnect_count = sum(NetTargetReconnectCount_d),\r\n  retransmit_count = sum(NetTargetRetransmitCount_d),\r\n  send_vol = sum(NetTargetSendMB_d),\r\n  receive_vol = sum(NetTargetReceiveMB_d)\r\n  by bin(TimeGenerated, $time_agg), App, Target = target, Port = NetTargetRemotePort_d\r\n| sort by App asc, Target asc , Port asc\r\n| extend target_full = strcat(App,\" -> \",Target,\":\",Port)\r\n| project TimeGenerated, target_full, reconnect_count\r\n| evaluate pivot(target_full, max(reconnect_count))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Retransmit count over time",
     "type": "timeseries",
     "description": "Select an app in the table above to filter this time chart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 232 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend target = coalesce(NetTargetRemoteName_s,NetTargetRemoteAddress_s)\r\n| summarize \r\n  retransmit_count = sum(NetTargetRetransmitCount_d)\r\n  by bin(TimeGenerated, $time_agg), App, Target = target, Port = NetTargetRemotePort_d\r\n| sort by App asc, Target asc , Port asc\r\n| extend target_full = strcat(App,\" -> \",Target,\":\",Port)\r\n| project TimeGenerated, target_full, retransmit_count\r\n| evaluate pivot(target_full, max(retransmit_count))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Send data volume over time",
     "type": "timeseries",
     "description": "Select an app in the table above to filter this time chart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend target = coalesce(NetTargetRemoteName_s,NetTargetRemoteAddress_s)\r\n| summarize \r\n  send_vol = sum(NetTargetSendMB_d),\r\n  receive_vol = sum(NetTargetReceiveMB_d)\r\n  by bin(TimeGenerated, $time_agg), App, Target = target, Port = NetTargetRemotePort_d\r\n| sort by App asc, Target asc , Port asc\r\n| extend target_full = strcat(App,\" -> \",Target,\":\",Port)\r\n| project TimeGenerated, target_full, send_vol\r\n| evaluate pivot(target_full, max(send_vol))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    },
    {
     "title": "Receive data volume over time",
     "type": "timeseries",
     "description": "Select an app in the table above to filter this time chart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 248 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "uberAgent_Process_NetworkTargetPerformance_CL\r\n| where $__timeFilter(TimeGenerated) \r\n| where ProcUser_s contains \"$User\"\r\n| where Computer contains \"$Computer\"\r\n| extend App = coalesce(AppId_s,ProcName_s)\r\n| where App contains \"$App\"\r\n| extend target = coalesce(NetTargetRemoteName_s,NetTargetRemoteAddress_s)\r\n| summarize \r\n  receive_vol = sum(NetTargetReceiveMB_d)\r\n  by bin(TimeGenerated, $time_agg), App, Target = target, Port = NetTargetRemotePort_d\r\n| sort by App asc, Target asc , Port asc\r\n| extend target_full = strcat(App,\" -> \",Target,\":\",Port)\r\n| project TimeGenerated, target_full, receive_vol\r\n| evaluate pivot(target_full, max(receive_vol))\r\n\r\n",
        "resources": [
         "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$workspace"
        ],
        "resultFormat": "logs",
        "timeColumn": "TimeGenerated"
       }
      }
     ]
    }
   ]
  }
 ]
}